# Generated by Django 5.2.6 on 2025-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_isbn_reservation_status_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
