# Generated by Django 5.2.6 on 2025-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reservation_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
